homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  customize: !include includes/customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: https://jdub01984ha.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
#  base_url: http://192.168.3.205:8123
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# emulated_hue (to accept voice commands from alexa)
emulated_hue:
  host_ip: 192.168.3.125

# Text to speech
tts:
  - platform: google

# Zigbee
zha:
  usb_path: /dev/ttyUSB1
  database_path: zigbee.db

# Device Tracker for Presence Detection
device_tracker: !include includes/device_trackers.yaml

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_bot_api
    default_channel: '#general'

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
camera: !include includes/cameras.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml
media_player: !include includes/media_players.yaml
input_boolean: !include includes/input_booleans.yaml
climate: !include includes/climate.yaml
scene: !include includes/scenes.yaml